const KEY = 'food-wheel-items-v2'
const HISTORY = 'food-wheel-history-v1'
const COLORS = ['#7fa982','#9bbf9d','#e5c879','#e89a7e','#86b8ae','#88aeb8','#a29abf','#c88778','#9aab7d','#d4aa76']
const TAGLINES = ['告别选择困难，轻松决定一餐','不用纠结吃啥，美味交给转盘','解决吃饭难题，随心享用美食','告别选择内耗，好好享受干饭','帮你摆脱纠结，吃好每一餐','纠结吃什么？交给转盘来决定','终结干饭选择困难症','不必苦苦纠结，干饭自有答案','选择交给转盘，快乐留给味蕾','专治 “不知道吃啥”','停止纠结，开启美味盲选','不用费脑，随机解锁好菜','不必纠结，好好吃饭','替你做决定，好好享用一餐','告别选择焦虑，好好吃饭','随机择好菜，食得自在','消解选择烦恼，好好干饭','一键告别 “吃什么” 难题','省去纠结，遇见合口美味','不必犹豫，美味即刻开奖']
const DEFAULTS = [['红烧肉','荤菜',['五花肉','葱','姜']],['宫保鸡丁','荤菜',['鸡胸肉','花生','黄瓜']],['番茄炒蛋','素菜',['番茄','鸡蛋']],['蒜蓉西兰花','素菜',['西兰花','蒜']],['清炒时蔬','素菜',['青菜','蒜']],['紫菜蛋花汤','汤菜',['紫菜','鸡蛋']],['番茄蛋汤','汤菜',['番茄','鸡蛋']],['蛋炒饭','主食',['米饭','鸡蛋']],['饺子','主食',['面粉','猪肉','白菜']],['麻婆豆腐','荤菜',['豆腐','猪肉','辣椒']]]
const FIXED_CATEGORIES = ['荤菜','素菜','汤菜','主食','小吃']

function uid(){ return Date.now().toString(36) + Math.random().toString(36).slice(2) }
function make(x){ return {id:uid(),name:x[0],category:x[1],ingredients:x[2] || [],lastUsedAt:0,useCount:0} }
function loadItems(){ const value=wx.getStorageSync(KEY); if(Array.isArray(value)&&value.length) return value; return DEFAULTS.map(make) }
function saveItems(items){ wx.setStorageSync(KEY, items) }
function parseIngredients(text){ return String(text || '').trim().split(/[,，、\n\s]+/).map(x=>x.trim()).filter(Boolean) }
function wheelLabel(name,index,total,size){
  const number=String(index+1).padStart(2,'0')
  const compact=size<=360
  if(total>24||(compact&&total>12)) return number
  if(total>12||compact) return String(name).slice(0,2)+(String(name).length>2?'…':'')
  return String(name).slice(0,6)+(String(name).length>6?'…':'')
}
function labelRadius(radius,total){ return total>24 ? radius*.84 : total>12 ? radius*.72 : radius*.64 }

Page({
  data:{
    mode:'wheel', tagline:TAGLINES[Math.floor(Math.random()*TAGLINES.length)], items:[], displayItems:[], searchText:'', categories:[], categoryOptions:[], currentCategory:'全部', categoryIndex:0, dishCategory:'荤菜', dishCategoryIndex:0, dishName:'', filtered:[], groups:[], result:null, spinning:false, ingredientText:'', ingredients:[], recipes:[], searched:false, importVisible:false, importText:'', wheelPx:300
  },
  onLoad(){ this.items=loadItems(); this.rotation=0; const info=wx.getSystemInfoSync(); this.canvasSize=300; this.setData({items:this.items,wheelPx:Math.max(260,Math.min(360,info.windowWidth-48))}); this.refreshCategories(); this.refreshWheel(); wx.nextTick(()=>this.drawWheel()) },
  refreshCategories(){ const categories=['全部',...Array.from(new Set(this.items.map(x=>x.category||'未分类')))]; const options=Array.from(new Set([...FIXED_CATEGORIES,...categories.filter(x=>x!=='全部'&&!FIXED_CATEGORIES.includes(x))])); let current=this.data.currentCategory; if(!categories.includes(current)){current='全部'} this.setData({categories,currentCategory:current,categoryIndex:categories.indexOf(current),categoryOptions:options,dishCategory:options[0],dishCategoryIndex:0}); this.refreshSearch(); },
  refreshSearch(){ const query=(this.data.searchText||'').trim().toLocaleLowerCase(); const displayItems=this.items.filter(x=>!query||String(x.name).toLocaleLowerCase().includes(query)).map(x=>({...x,sourceIndex:this.items.indexOf(x)})); this.setData({displayItems}); },
  refreshWheel(){ const filtered=this.data.currentCategory==='全部'?this.items:this.items.filter(x=>x.category===this.data.currentCategory); this.setData({filtered,groups:this.makeGroups()}); wx.nextTick(()=>this.drawWheel()) },
  makeGroups(){ const map={}; this.items.forEach(x=>{const c=x.category||'未分类'; if(!map[c])map[c]=[]; map[c].push(x)}); return Object.keys(map).map(category=>({category,open:this.data.groups.find(g=>g.category===category)?.open || (this.data.currentCategory!=='全部'&&category===this.data.currentCategory),items:map[category].map(x=>({...x,number:String(this.items.indexOf(x)+1).padStart(2,'0')}))})) },
  switchMode(e){ const mode=e.currentTarget.dataset.mode; this.setData({mode}); if(mode==='wheel')wx.nextTick(()=>this.drawWheel()) },
  onDishNameInput(e){ this.setData({dishName:e.detail.value}) },
  onSearchInput(e){ this.setData({searchText:e.detail.value}); this.refreshSearch() },
  onSearchConfirm(e){ this.setData({searchText:e.detail.value}); this.refreshSearch() },
  onSearchBlur(e){ this.setData({searchText:e.detail.value}); this.refreshSearch() },
  onEditNameInput(e){},
  onEditNameConfirm(e){ this.commitName(e) },
  onEditNameBlur(e){ this.commitName(e) },
  commitName(e){ const index=Number(e.currentTarget.dataset.index),item=this.items[index],name=String(e.detail.value||'').trim(); if(!item||!name)return; if(item.name!==name){item.name=name;saveItems(this.items);this.setData({items:this.items});this.refreshCategories();this.refreshWheel()} },
  onDishCategoryChange(e){ const index=Number(e.detail.value); this.setData({dishCategoryIndex:index,dishCategory:this.data.categoryOptions[index]}) },
  onCategoryChange(e){ const index=Number(e.detail.value); this.setData({categoryIndex:index,currentCategory:this.data.categories[index]}); this.refreshWheel() },
  addDish(){ const name=this.data.dishName.trim(); if(!name){wx.showToast({title:'请输入菜名',icon:'none'});return} this.items.push(make([name,this.data.dishCategory,[]])); saveItems(this.items); this.setData({items:this.items,dishName:''}); this.refreshCategories(); this.refreshWheel() },
  editDish(e){ const index=Number(e.currentTarget.dataset.index); const item=this.items[index]; wx.showModal({title:'修改菜名',editable:true,content:item.name,success:r=>{if(r.confirm&&r.content.trim()){item.name=r.content.trim();saveItems(this.items);this.setData({items:this.items});this.refreshWheel()}}}) },
  deleteDish(e){ const index=Number(e.currentTarget.dataset.index); if(this.items.length<=1)return; this.items.splice(index,1); saveItems(this.items); this.setData({items:this.items}); this.refreshCategories(); this.refreshWheel() },
  openImportPanel(){ this.setData({importVisible:true}) },
  closeImportPanel(){ this.setData({importVisible:false,importText:''}) },
  onImportTextInput(e){ this.setData({importText:e.detail.value}) },
  importPastedText(){ if(!this.data.importText.trim()){wx.showToast({title:'请先粘贴菜单内容',icon:'none'});return} this.parseImported(this.data.importText); this.setData({importVisible:false,importText:''}) },
  toggleGroup(e){ const category=e.currentTarget.dataset.category; const groups=this.data.groups.map(g=>g.category===category?({...g,open:!g.open}):g); this.setData({groups}) },
  drawWheel(){ const query=wx.createSelectorQuery().in(this); query.select('#wheelCanvas').fields({node:true,size:true}).exec(res=>{ if(res&&res[0]&&res[0].node){ this.canvas=res[0].node; this.canvasSize={w:res[0].width,h:res[0].height}; const ratio=wx.getSystemInfoSync().pixelRatio||1; this.canvas.width=Math.round(res[0].width*ratio); this.canvas.height=Math.round(res[0].height*ratio); this.canvas.getContext('2d').scale(ratio,ratio); this.drawCurrent() } else { this.canvas=null; this.legacyCtx=wx.createCanvasContext('wheelCanvas',this); this.canvasSize={w:300,h:300}; this.drawCurrent() } }) },
  drawCurrent(){ if(this.canvas) this.drawNode(this.canvasSize.w,this.canvasSize.h,this.rotation||0); else if(this.legacyCtx)this.drawLegacy(this.legacyCtx,this.canvasSize.w,this.rotation||0) },
  drawLegacy(ctx,size,rotation){ const arr=this.data.filtered,n=arr.length,r=size/2-8;ctx.clearRect(0,0,size,size);if(!n){ctx.setFillStyle('#bbb');ctx.beginPath();ctx.arc(size/2,size/2,r,0,Math.PI*2);ctx.fill();ctx.draw();return}const slice=Math.PI*2/n;arr.forEach((x,i)=>{const a=rotation+i*slice;ctx.beginPath();ctx.moveTo(size/2,size/2);ctx.arc(size/2,size/2,r,a,a+slice);ctx.setFillStyle(COLORS[i%COLORS.length]);ctx.fill();ctx.setFillStyle('#fff');ctx.setFontSize(size<=360||n>24?12:n>12?13:15);ctx.setTextAlign('center');const label=wheelLabel(x.name,i,n,size),lr=labelRadius(r,n);ctx.fillText(label,size/2+Math.cos(a+slice/2)*lr,size/2+Math.sin(a+slice/2)*lr)});ctx.setFillStyle('#df705d');ctx.beginPath();ctx.moveTo(size/2-14,0);ctx.lineTo(size/2+14,0);ctx.lineTo(size/2,24);ctx.closePath();ctx.fill();ctx.setFillStyle('#26332a');ctx.setFontSize(13);ctx.setTextAlign('center');ctx.fillText(this.data.currentCategory,size/2,size/2-9);ctx.setFontSize(12);ctx.fillText(`${n}道`,size/2,size/2+10);ctx.draw() },
  drawNode(w,h,rotation){const ctx=this.canvas.getContext('2d'),arr=this.data.filtered,n=arr.length,r=Math.min(w,h)/2-8;ctx.clearRect(0,0,w,h);if(!n)return;const slice=Math.PI*2/n;arr.forEach((x,i)=>{const a=rotation+i*slice;ctx.beginPath();ctx.moveTo(w/2,h/2);ctx.arc(w/2,h/2,r,a,a+slice);ctx.closePath();ctx.fillStyle=COLORS[i%COLORS.length];ctx.fill();ctx.strokeStyle='rgba(255,255,255,.5)';ctx.stroke();ctx.fillStyle='#fff';ctx.font=`bold ${w<=360||n>24?12:n>12?13:15}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';const label=wheelLabel(x.name,i,n,w),lr=labelRadius(r,n);ctx.fillText(label,w/2+Math.cos(a+slice/2)*lr,h/2+Math.sin(a+slice/2)*lr)});ctx.fillStyle='#df705d';ctx.beginPath();ctx.moveTo(w/2-14,0);ctx.lineTo(w/2+14,0);ctx.lineTo(w/2,24);ctx.closePath();ctx.fill();ctx.beginPath();ctx.arc(w/2,h/2,r*.18,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.fillStyle='#26332a';ctx.textBaseline='middle';ctx.font='bold 12px sans-serif';ctx.textAlign='center';ctx.fillText(this.data.currentCategory,w/2,h/2-8);ctx.font='bold 11px sans-serif';ctx.fillText(`${n}道`,w/2,h/2+10) },
  spin(){ if(this.data.spinning||this.data.filtered.length<2){if(this.data.filtered.length<2)wx.showToast({title:'当前分类至少需要两道菜',icon:'none'});return} const pool=this.data.filtered,win=pool[Math.floor(Math.random()*pool.length)],index=pool.indexOf(win),slice=Math.PI*2/pool.length,target=-Math.PI/2-(index+.5)*slice,start=this.rotation||0,delta=((target-start)%(Math.PI*2)+Math.PI*2)%(Math.PI*2)+Math.PI*2*5,duration=2200,t0=Date.now();this.setData({spinning:true,result:null});clearInterval(this.spinTimer);this.spinTimer=setInterval(()=>{const p=Math.min(1,(Date.now()-t0)/duration),ease=1-Math.pow(1-p,3);this.rotation=start+delta*ease;this.drawCurrent();if(p>=1){clearInterval(this.spinTimer);this.spinTimer=null;win.lastUsedAt=Date.now();win.useCount=(win.useCount||0)+1;saveItems(this.items);this.setData({spinning:false,result:win})}},16) },
  onIngredientInput(e){this.setData({ingredientText:e.detail.value})},
  findRecipes(){const input=parseIngredients(this.data.ingredientText).map(x=>x.toLowerCase());const recipes=this.items.map(x=>{const have=(x.ingredients||[]).filter(i=>input.some(v=>i.toLowerCase().includes(v)||v.includes(i.toLowerCase())));const missing=(x.ingredients||[]).filter(i=>!have.includes(i));return {...x,haveText:have.join('、'),missingText:missing.join('、'),score:have.length/(x.ingredients||[]).length}}).filter(x=>x.haveText).sort((a,b)=>b.score-a.score).slice(0,8);this.setData({ingredients:input,recipes,searched:true})},
  showFormat(){wx.showModal({title:'文本导入格式',content:'每行一道菜，格式为：菜品·分类\n\n红烧肉·荤菜\n番茄炒蛋·素菜\n紫菜蛋花汤·汤菜\n\n空行会自动忽略。',showCancel:false})},
  importMenu(){wx.chooseMessageFile({count:1,type:'file',success:res=>{const file=res.tempFiles&&res.tempFiles[0];if(!file){wx.showToast({title:'没有选择文件',icon:'none'});return}const path=file.path||file.tempFilePath||'';const name=file.name||path;if(!/\.txt$/i.test(name)){wx.showToast({title:'只能导入 TXT 文件',icon:'none'});return}wx.getFileSystemManager().readFile({filePath:path,encoding:'utf8',success:r=>this.parseImported(r.data),fail:()=>wx.showToast({title:'文件读取失败，请改用粘贴导入',icon:'none'})})},fail:()=>wx.showToast({title:'请选择 TXT 文件，或使用粘贴导入',icon:'none'})})},
  parseImported(text){const added=[],errors=[];String(text).split(/\r?\n/).forEach((line,i)=>{const value=line.replace(/[\uFEFF\u200B\u200C\u200D]/g,'').trim();if(!value)return;const match=value.match(/^(.+?)[·•・⋅:：](.+)$/);if(!match||!match[1].trim()||!match[2].trim()){errors.push(i+1);return}const name=match[1].trim(),category=match[2].trim();if(!this.items.some(x=>x.name===name&&x.category===category)){const item=make([name,category,[]]);this.items.push(item);added.push(item)}});saveItems(this.items);this.setData({items:this.items});this.refreshCategories();this.refreshWheel();let message=`成功导入 ${added.length} 道菜品`;if(errors.length)message+=`，第 ${errors.join('、')} 行格式有误`;wx.showModal({title:'导入结果',content:message,showCancel:false})},
  exportMenu(){const text=this.items.map(x=>`${x.name}·${x.category||'未分类'}`).join('\r\n')+'\r\n';const path=`${wx.env.USER_DATA_PATH}/我的菜谱.txt`;wx.getFileSystemManager().writeFile({filePath:path,data:text,encoding:'utf8',success:()=>wx.openDocument({filePath:path,fileType:'txt',showMenu:true,fail:()=>wx.setClipboardData({data:text,success:()=>wx.showToast({title:'菜单已复制，可粘贴保存',icon:'none'})})}),fail:()=>wx.setClipboardData({data:text,success:()=>wx.showToast({title:'菜单已复制，可粘贴保存',icon:'none'})})})}
})
